version: '3.9'

services:
  backend:
    build: .
    volumes:
      - .:/app
      - ./uploads:/app/uploads  # <-- bind mount
    ports:
      - "5000:5000"
    env_file:
      - .env
    command: flask run --host=0.0.0.0 --port=5000 --reload